#!/usr/bin/env python3
"""Generate the bundled BMP simple-uppercase table from pinned Unicode data (offline)."""
import argparse, hashlib, pathlib, subprocess
ROOT=pathlib.Path(__file__).resolve().parents[1]
SHA='2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c'
p=argparse.ArgumentParser();p.add_argument('source',type=pathlib.Path);p.add_argument('--check',action='store_true');args=p.parse_args()
raw=args.source.read_bytes();assert hashlib.sha256(raw).hexdigest()==SHA,'Expected Unicode 17.0.0 UnicodeData.txt'
pairs=[]
for line in raw.decode().splitlines():
    fields=line.split(';');point=int(fields[0],16)
    if point<=0xffff and fields[12]:
        target=int(fields[12],16);assert target<=0xffff;pairs.append((point,target))
ranges=[];pos=0
while pos<len(pairs):
    first,upper=pairs[pos];last=first;delta=upper-first;step=1
    if pos+1<len(pairs) and pairs[pos+1][1]-pairs[pos+1][0]==delta and pairs[pos+1][0]-first in (1,2):step=pairs[pos+1][0]-first
    pos+=1
    while pos<len(pairs) and pairs[pos][0]-last==step and pairs[pos][1]-pairs[pos][0]==delta:
        last=pairs[pos][0];pos+=1
    ranges.append((first,last,step,delta))
assert [(point,point+delta) for first,last,step,delta in ranges for point in range(first,last+1,step)]==pairs
source='''// Generated by scripts/windows-case.py from Unicode 17.0.0 UnicodeData.txt.
// https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt
// SHA-256: '''+SHA+'''
// Unicode License V3: see THIRD_PARTY_NOTICES.md. No host-locale dependency.
// Each range is {first, last, stride, uppercase delta}; unmapped units retain their value.
const ranges = [_][4]i32{
'''+''.join(f'    .{{ 0x{first:x}, 0x{last:x}, {step}, {delta} }},\n' for first,last,step,delta in ranges)+'''};

pub fn upper(unit: u16) u16 {
    var lo: usize = 0;
    var hi: usize = ranges.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        if (ranges[mid][1] < unit) lo = mid + 1 else hi = mid;
    }
    if (lo == ranges.len) return unit;
    const entry = ranges[lo];
    const offset = @as(i32, unit) - entry[0];
    if (offset < 0 or @mod(offset, entry[2]) != 0) return unit;
    return @intCast(@as(i32, unit) + entry[3]);
}
'''
formatted=subprocess.check_output(['zig','fmt','--stdin'],input=source.encode())
target=ROOT/'src/windows_upper.zig'
if args.check:assert target.read_bytes()==formatted,'Regenerate src/windows_upper.zig'
else:target.write_bytes(formatted)
print(f'Unicode 17.0.0: {len(pairs)} BMP mappings in {len(ranges)} checked ranges')
